### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by Oddball777** [GraphingLib/GraphingLib#6]
### Fits
- [x] #15
- [ ] Create fit for arbitrary function which is passed as an argument
- [x] #64
- [x] #60
- [x] #43
- [x] #10
- [x] #57
- [x] #56
- [x] #54
- [x] Add missing tests to gaussian fit

### Classes
- [x] #7
- [x] #11
- [ ] #36
- [x] #24
- [ ] Implement derivative and integral curves
- [x] Add "default" options to from_function method
- [ ] Interpolate a point on a curve (get y from x, and get x's from y)
- [ ] Possibility to add grid to figure
- [ ] Heatmap from_function
- [x] #19
- [x] #20
- [x] #17
- [x] #71
- [x] #75

### Other
- [x] #8
- [ ] Find a way to change the axes with custom text
- [x] #12
- [x] #41
- [x] #22
- [ ] Multiple plots on same figure
- [ ] Specify font size
- [ ] #34
- [x] #35
- [x] #50
- [x] #62
- [x] #77

### Documentation
- [ ] Add docstrings everywhere
- [x] #68
- [x] #69
